version: '3.8'

services:
  backend:
    image: python:3.10-slim
    container_name: flask-backend
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

